set nocompatible

" Initial Setup (Pathogen)
filetype off
call pathogen#infect()
call pathogen#helptags()
filetype plugin indent on
set modelines=0

" Look and Feel
syntax on
filetype indent plugin on
set number
set background=dark
colorscheme harph
set colorcolumn=80
set cursorline
set list
set ruler

" Spacing and Indentation
set tabstop=4
set shiftwidth=4
set expandtab
set softtabstop=4
set smartindent
set smarttab
set autoindent

" Find/Search 
set hlsearch
set incsearch
set showmatch


" Errors Handling
set visualbell  " don't beep
set noerrorbells  " don't beep

" Editor
set wildignore=*.swp,*.bak,*.pyc,*/.git/*
set wildignore+=*/tmp/*,*.so,*.zip
set nobackup
set noswapfile

if !exists("*TrimWhiteSpace")
    " Removes trailing spaces
    function TrimWhiteSpace()
      %s/\s*$//
      ''
    :endfunction
endif


" My keys
map <F8> :call TrimWhiteSpace()<CR>
map <F1> :tabprevious<CR>
map <F2> :tabnext<CR>
map <F3> :tabclose<CR>
